### ISSUE TITLE
Shortcuts to websites

### ISSUE THREAD

**Issue by Dhendon** [nvsnkv/dns-override#2]
Hey,

I'm trying to use DNS Override to redirect m/ to mail.google.com as well as other shortcuts to access websites, but I keep getting "m not found" when I try this. Is there a way to use this product in that manner?

thanks!

**Comment by nvsnkv** [comment]
Hi!
Unfortunately, you can't create shortcucts like this with DNS Override. 
This extension simply replaces domains in every matched url found on **loaded page**. It doesn't works with omnibox.

**Comment by Dhendon** [comment]
Ahh, shame. Thanks for the response! Best of luck with the project

**Comment by chapgaga** [comment]
can this extension work on chrome 71?
